version: '3'

services:
  postgres-compose:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456789!'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data:Z
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'teste@teste.com'
      PGADMIN_DEFAULT_PASSWORD: '123456789!'
    ports:
      - '16543:80'
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

volumes:
  postgres-data:
      external: true

networks:
  postgres-compose-network:
    driver: bridge
